---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/iconUrl: "img/icons/camel.svg"
  labels:
    expose: "true"
    provider: "fabric8"
    project: "fis-demo"
    version: "1.0.0-SNAPSHOT"
    group: "org.mycompany"
  name: "fis-demo"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "fis-demo"
    provider: "fabric8"
    group: "org.mycompany"
